### ISSUE TITLE
Mosfet equivalent for 4 channels project

### ISSUE THREAD

**Issue by noisemaker00** [Nikfinn99/diyHue_PCB-Files#1]
Hi,
could you please suggest a list of equivalent mosfet for the project with 4 channels? Or the characteristics they must have.
Thanks a lot

**Comment by Nikfinn99** [comment]
Hi if you want to use only four channels you can just leave the fifth mosfet empty. 
Basically you can use almost any **n-channel** mosfet that uses a **TO-220 package.** 
The mosfets should have a maximum current of **more than 5A** and they have to get activated using only a **3.3V signal on the Gate** pin.

The N-Mos that i chose in the Parts.xlxs file a pretty good mosfets but they are also not the cheapest ones. 
You can just send a link to the datasheet of the mosfet you want to use and i can tell you, if it will work.

Suggesting specific mosfets is very difficult as there are so many of them that just differ in small details.
